spring.application.name=email-writer-sb
# Using the stable V1 endpoint
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent
gemini.api.key=AIzaSyDq8LUQtcAZ7DA9BjJ7-lHaQ6QzElovr54